on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  tests:
    uses: ./.github/workflows/tests.yaml
    secrets:
      ACR_SECRET: ${{ secrets.ACR_SECRET }}
      DMSS_DEPLOY_KEY: ${{ secrets.DMSS_DEPLOY_KEY }}


